CREATE TABLE `user` (
`USERID`  int(11) NOT NULL AUTO_INCREMENT ,
`USERNAME`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`PASSWORD`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`SALT`  varchar(8) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`CTIME`  datetime NULL DEFAULT NULL ,
PRIMARY KEY (`USERID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=12
ROW_FORMAT=COMPACT
;

CREATE TABLE `role` (
`ROLEID`  int(11) NOT NULL AUTO_INCREMENT ,
`ROLENAME`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`ROLEID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=4
ROW_FORMAT=COMPACT
;

CREATE TABLE `user_role` (
`USERID`  int(11) NOT NULL ,
`ROLEID`  int(11) NOT NULL ,
PRIMARY KEY (`USERID`, `ROLEID`),
FOREIGN KEY (`USERID`) REFERENCES `user` (`USERID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
FOREIGN KEY (`ROLEID`) REFERENCES `role` (`ROLEID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
INDEX `roleId` (`ROLEID`) USING BTREE 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=COMPACT
;


CREATE TABLE `permission` (
`PERMISSIONID`  int(11) NOT NULL ,
`PERMISSIONNAME`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`PERMISSIONID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=COMPACT
;

CREATE TABLE `role_permission` (
`ROLEID`  int(11) NOT NULL ,
`PERMISSIONID`  int(11) NOT NULL ,
PRIMARY KEY (`ROLEID`, `PERMISSIONID`),
FOREIGN KEY (`ROLEID`) REFERENCES `role` (`ROLEID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
FOREIGN KEY (`PERMISSIONID`) REFERENCES `permission` (`PERMISSIONID`) ON DELETE RESTRICT ON UPDATE RESTRICT,
INDEX `PERMISSIONID` (`PERMISSIONID`) USING BTREE 
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=COMPACT
;


